language: elixir

elixir:
  - 1.3.4
  - 1.4.0
  - 1.5.1
  - 1.8.1

otp_release:
  - 18.2
  - 19.2

matrix:
  # We are only interested on the newest/oldest pair
  exclude:
    - elixir: 1.4.0
      otp_release: 18.2
    - elixir: 1.3.4
      otp_release: 19.2
    - elixir: 1.5.1
      otp_release: 18.2

sudo: false

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

script:
  - mix test
